version: "3"
services:
  app:
    env_file:
      - streamlit/.env
    container_name: frontend
    build:
      dockerfile: streamlit/Dockerfile
    command: "streamlit run --server.port 8501 --server.enableCORS false Home.py"
    ports:
      - "8501:8501"
    networks:
      - airflow_default
    image: frontend:latest

  api:
    env_file:
      - fastapi/.env
    container_name: backend
    build:
      dockerfile: fastapi/Dockerfile
    command: "uvicorn apis:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    networks:
      - airflow_default
    image: backend:latest

networks:
  airflow_default:
    external: true