name: FastAPI Unit Tests

on:
  push:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    env:
      secret: ${{ secrets.secret }}
      algorithm: ${{ secrets.algorithm }}
      snowflake_password: ${{ secrets.snowflake_password }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r fastapi/requirements.txt

    - name: Run unit tests
      env:
        PYTHONPATH: ./fastapi
      run: pytest fastapi/test_apis.py --cov=. --cov-report html
      
    - name: Code Coverage
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
